### ISSUE TITLE
I can't use it, where is the password to SFTP?

### ISSUE THREAD

**Issue by kaiogoncarvalho** [imjonos/wsl2-docker-start#1]

**Comment by imjonos** [comment]
Hi
You need install ssh server inside wsl 
I used Ubuntu
 
sudo apt install openssh-server

And after config it
Something like this https://www.illuminiastudios.com/dev-diaries/ssh-on-windows-subsystem-for-linux/

Also after started wsl you need to start all services 
This is my script for it https://github.com/imjonos/wsl2-lamp-tools/blob/master/start-lamp.sh
